server:
  port: 80
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: team.redrock.microboot.vo            # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/crud?useUnicode=true&characterEncoding=utf-8           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: kk123456                            # 数据库连接密码
    filters: stat,wall,log4j
    druid:
      connection-init-sqls: set names utf8mb4;


#  resources:
#    static-locations: /jsp/
#    dbcp2:                                          # 进行数据库连接池的配置
#      min-idle: 5                                   # 数据库连接池的最小维持连接数
#      initial-size: 5                               # 初始化提供的连接数
#      max-total: 5                                  # 最大的连接数
#      max-wait-millis: 200                          # 等待连接获取的最大超时时间
#jsp 支持
spring.mvc.view.prefix: /WEB-INF/
spring.mvc.view.suffix: .jsp
spring.thymeleaf.cache: false
spring.thymeleaf.enabled: false
